<a href="https://colab.research.google.com/github/MHaseeb43/Age-Calculator/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


### Introduction to Tensor

## Creating Tensor

In [130]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [131]:
scalar.ndim

0

In [132]:
scalar.item()

7

In [133]:
# Vector

Vector = torch.tensor([1,2])
Vector
Vector.ndim

1

In [134]:
Vector.shape

torch.Size([2])

In [135]:
# MATRICS

Matrics = torch.tensor([[1,2],[3,4]])
Matrics[1]
Matrics.ndim
Matrics.shape

torch.Size([2, 2])

In [136]:
# TENSOR

Tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
Tensor2 = torch.tensor([[[1,3],[2,4]]])

Tensor2.ndim
Tensor2.shape

torch.Size([1, 2, 2])

### Random Tensors

In [137]:
# Create a random tensor of size
Random = torch.rand(3,4)
Random
Random.ndim

2

In [138]:
# Creating random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(224,334,3) # Height, Width, Colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 334, 3]), 3)

### Zeros and Ones

In [139]:
Zeros = torch.zeros(3,4)
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [140]:
Ones = torch.ones(2,4)
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a raange of tensors and tensors-like.

In [141]:
# Use torch.range(), get deprecated message, use torch.arange()
range = torch.range(start=0, end=10,step=1)
range

/tmp/ipython-input-3764767912.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(start=0, end=10,step=1)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [142]:
# Creating tensors like

ten_ones = torch.ones_like(input=range)
ten_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Tensors DataType
####Note: Tensor dataType is one of the 3 big errors you'll run into with pyTorch & Deep Learning.
1- Tensors not right datatype
2- Tensors not right shape
3- Tensors not on the right device


In [143]:
# Float 32 tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # What datetype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on CPU or GPA
                               requires_grad=False #Whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([1., 2., 3.])

In [144]:
 float_16_tensor = float_32_tensor.type(torch.half)
 float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [145]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

## Tensor Attributes

*   1- Tensors not right datatype  - to get datatype from tensor can use  tensor.dtype
*   2- Tensors not right shape. - to get the shape from tensor, can use tensor.shape
*   3- Tensors not on the right device - to get the device from a tensor, can use tensor.device



In [146]:
# Create a Random Tensor

Rand = torch.rand((3,2), dtype=torch.float16, device=None)
Rand

tensor([[0.3740, 0.4424],
        [0.4507, 0.0850],
        [0.2070, 0.0435]], dtype=torch.float16)

In [147]:
# Find out detail about some tensor

print(f"Datatype of tensor: {Rand.dtype}")
print(f"Shape of tensor: {Rand.shape}")
print(f"Device of tensor: {Rand.device}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 2])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)
Tensor operations included

*   Addition
*   Subtraction
*   Multiplication (Element Wise)
*   Division
*   Matrix Multiplication



In [148]:
### Manipulating Tensors (tensor operations)

tensor = torch.tensor([1,2,3])
tensor + 10
tensor - 12
tensor * 8

tensor([ 8, 16, 24])

### Matrix Multplication

Two main ways of performing multiplication in neural network and deep learning.   

*   Element wise Multiplication
*   Matrix Multiplication

More Information on multiplying matrices.

There are two main rules that performing matrix multiplication needs to satisfy:

1- The **inner dimension** must match:

*   (3,2) * (3,2) Won't work
*   (2,3) * (3,2) Will work
*   (3,2) * (2,3) Will work

2- The resulting matrix has the shape of the outer dimensions:

*   (3,2) * (3,2) -> (2,2)
*   (3,2) * (2,3) -> (3,3)




In [149]:
# Element Wise Multiplication.
print(tensor, "*", tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [150]:
# Matrix Multiplication
Matrics = torch.matmul(tensor, tensor)
Matrics

tensor(14)

In [151]:
#

Mul = torch.matmul(torch.randn(2,3), torch.randn(3,2))
Mul

tensor([[ 4.7531, -1.0645],
        [ 0.3941,  0.3764]])

In [152]:
# Shape for matrix multiplication.
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B.T) #torch.mm is the short form of torch.matmul. We get the shape error here.

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [153]:
# One of the solution is to take the transpose of the tensor.
torch.mm (tensor_A.T,tensor_B)


tensor([[ 76, 103],
        [100, 136]])

In [154]:
 tensor_B.T.shape


torch.Size([2, 3])

### Finding min, max, mean and sum etc (Tensor Aggregate)

In [155]:
# Creating a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [156]:
# Find the min
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [157]:
#  Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [158]:
# Find the sum. Both are same you can use any of them.
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [159]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [160]:
# Find the position in tensor that has the minimum value with argmin() -> return index position
x.argmin()

tensor(0)

In [161]:
x.argmax()


tensor(9)

In [162]:
x[0]

tensor(1)

In [163]:
x[9]

tensor(91)

# Reshaping, stacking, squeezing and unsqueezing tensors.

*   Reshape - reshape an input tensor to a defined shape.
*   View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
*   Stacking - combine multiple tensor on top of each other or side by side.
*   Squeeze -  remove all `1` dimensions from a tensor.
*   Unsqueeze - add a 1 dimension to a target tensor.
*   Permute - Return a view of the input with dimension permuted (swapped) in a certain way.


In [164]:
# Reshape - One more thing that we can only use the same dimensions.
x_reshape = x.reshape(1,10)
x_reshape

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [165]:
# Change the view.
z = x.view(1,10)
z

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [166]:
# Changing z changes x (because a view of a tensor shares the same memory as the original).
z[: , 0] = 34
x,z

(tensor([34, 11, 21, 31, 41, 51, 61, 71, 81, 91]),
 tensor([[34, 11, 21, 31, 41, 51, 61, 71, 81, 91]]))

In [167]:
# Stack tensors on top of each other.
x_stacked = torch.stack([x,x,x], dim=1)
x_stacked

tensor([[34, 34, 34],
        [11, 11, 11],
        [21, 21, 21],
        [31, 31, 31],
        [41, 41, 41],
        [51, 51, 51],
        [61, 61, 61],
        [71, 71, 71],
        [81, 81, 81],
        [91, 91, 91]])

In [168]:
# Squeeze - Remove all the single dimension from a target tensor. See we remove the 1 from the tensor.
x_squeeze = x_reshape.squeeze()
x_squeeze
x_squeeze.shape

torch.Size([10])

In [169]:
#Unsqueez - Add a single dimension to a target tensor at a specific dim (dimension).
print(f"Previous tensor: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeeze.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([34, 11, 21, 31, 41, 51, 61, 71, 81, 91])
Previous shape: torch.Size([10])

New tensor: tensor([[34, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
New shape: torch.Size([1, 10])


In [170]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order.
x_original = torch.rand(size=(22,34,5)) #[Height, width, colour_channel]
x_permute = x_original.permute(2,0,1)
print(f"Pervious shape: {x_original.shape}")
print(f"New shape: {x_permute.shape}")


Pervious shape: torch.Size([22, 34, 5])
New shape: torch.Size([5, 22, 34])


##Indexing (selecting data from tensors)
Index with pytorch is similar to indexing with Numpy.

In [171]:
# Create a tensor.
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [172]:
# Getting the elements from the tensors.
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [173]:
x[0,0]

tensor([1, 2, 3])

In [174]:
x[0][1][2]  #Upper cell and this using different format. You can use any of these.

tensor(6)

In [175]:
# You can also use the ":" to select "all" of a target dimension.
x[:,0]

tensor([[1, 2, 3]])

In [176]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension.
x[:,:,1]

tensor([[2, 5, 8]])

In [177]:
# Assignment
x[:,:,2]  # Return 3,6,9
x[:,2,2] # Return 9.

tensor([9])

## PyTorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.


*   Data in NumPy , want in PyTorch tensor -> torch.from_numpy(ndarray).
*   PyTorch tensor -> NumPy -> torch.Tensor.numpy().



In [182]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array.dtype, tensor.dtype



(dtype('float64'), torch.float64)

In [184]:
  import torch

  # Set a random seed.
  RANDOM_SEED = 42
  torch.manual_seed(RANDOM_SEED)
  random_tensor_C = torch.rand(3,4)
  torch.manual_seed(RANDOM_SEED)
  random_tensor_D = torch.rand(3,4)
  print(random_tensor_C)
  print(random_tensor_D)
  print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
